### ISSUE TITLE
Roadmap / todo

### ISSUE THREAD

**Issue by szszszsz** [dbeef/blue#1]
Hi!

Do you have any roadmap or to do list? I would happily support you in the further development - if you have anything to do left that is :-)

**Comment by dbeef** [comment]
Hello

I will upload a roadmap soon, but as for now, you could implement creating framebuffers and provide a sample to the `examples` directory.

I imagine it would consist of adding a new kind of entity in `GpuEntities.hpp`, another overload of `submit` in the `GpuSystem`, and a handler involving a few OpenGL commands - it would be a matter of copy-pasting from my old repository:

https://github.com/dbeef/opengl-playground/blob/master/src/blue/Framebuffer.cpp

Then add a framebuffer id to the RenderEntity - and bind passed framebuffer in the `Renderer.cpp`, where processing of RenderEntities happens.

As a sample, a gaussian blur would be nice. For example, first create one render entity drawing a triangle to the passed framebuffer, the second one would bind the framebuffer as a texture and do post-processing in the shader (you can find public domain one-pass gaussian blur GLSL shaders on the web) and draw result to the screen.

"Rendering triangle" sample could be a base for your new sample.

Here's a good source for OpenGL reference:
https://learnopengl.com/Advanced-OpenGL/Framebuffers

**Comment by szszszsz** [comment]
Hi!

Will look into it! I would imagine though with the lack of experience with OpenGL it will take some time. Could you share please, where the roadmap has been uploaded?
